export const Font = {
  regularH1_42: {
    fontSize: "42px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "42px",
  },
  regularH2_35: {
    fontSize: "35px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "42px",
  },
  regularH3_29: {
    fontSize: "29px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "34px",
  },
  regularH4_24: {
    fontSize: "24px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "28px",
  },
  regularH5_20: {
    fontSize: "20px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "24px",
  },
  regular17: {
    fontSize: "17px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "20px",
  },
  regular14: {
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "16px",
  },
  regular13: {
    fontSize: "13px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "15px",
  },
  regular12: {
    fontSize: "12px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "14px",
  },
  regular10: {
    fontSize: "10px",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "12px",
  },
  mediumH1_42: {
    fontSize: "42px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "50px",
  },
  mediumH2_35: {
    fontSize: "35px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "42px",
  },
  mediumH3_29: {
    fontSize: "29px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "34px",
  },
  mediumH4_24: {
    fontSize: "24px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "28px",
  },
  mediumH5_20: {
    fontSize: "20px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "24px",
  },
  medium17: {
    fontSize: "17px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "20px",
  },
  medium14: {
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "16px",
  },
  medium12: {
    fontSize: "12px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "14px",
  },
  medium10: {
    fontSize: "10px",
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "12px",
  },
  boldH1_42: {
    fontSize: "42px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "50px",
  },
  boldH2_35: {
    fontSize: "35px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "42px",
  },
  boldH3_29: {
    fontSize: "29px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "34px",
  },
  boldH4_24: {
    fontSize: "24px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "28px",
  },
  boldH5_20: {
    fontSize: "20px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "24px",
  },
  bold17: {
    fontSize: "17px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "20px",
  },
  bold14: {
    fontSize: "14px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "16px",
  },
  bold12: {
    fontSize: "12px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "14px",
  },
  bold10: {
    fontSize: "10px",
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "12px",
  },
  italic12: {
    fontSize: "12px",
    fontFamily: "Inter",
    fontStyle: "italic",
    lineHeight: "14px",
  },
  italic17: {
    fontSize: "17px",
    fontFamily: "Inter",
    fontStyle: "italic",
    lineHeight: "20px",
  },
}
